# Generated by Django 4.1.1 on 2023-01-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCS_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='')),
                ('good', models.IntegerField()),
                ('read', models.IntegerField()),
                ('readtext', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='MyImage',
        ),
    ]
