# Generated by Django 4.1.1 on 2023-01-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCS_app', '0003_image_delete_snsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
